# Generated by Django 3.2 on 2025-01-28 10:50

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20250125_1651'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='review',
            managers=[
                ('comments', django.db.models.manager.Manager()),
            ],
        ),
    ]
