# Generated by Django 3.2 on 2025-01-28 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_alter_review_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='review',
            managers=[
            ],
        ),
    ]
